app:
  csv-folder: /Users/shiraishitoshio/bookmaker/csv/
  output-csv-folder: /Users/shiraishitoshio/bookmaker/outputs/
  team-csv-folder: /Users/shiraishitoshio/bookmaker/teams_by_league/
  future-csv-folder: /Users/shiraishitoshio/bookmaker/future/
  b001-json-folder: /Users/shiraishitoshio/bookmaker/json/b001/
  
spring:
  flyway:
    enabled: true
    datasource:
      url: jdbc:postgresql://localhost:54320/soccer_bm
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true