app:
  csv-folder: /Users/shiraishitoshio/bookmaker/csv/
  output-csv-folder: /Users/shiraishitoshio/bookmaker/outputs/
  team-csv-folder: /Users/shiraishitoshio/bookmaker/teams_by_league/
  future-csv-folder: /Users/shiraishitoshio/bookmaker/future/
  b001-json-folder: /Users/shiraishitoshio/bookmaker/json/b001/
  
process:
  python:
    root: /Users/shiraishitoshio/bookmaker/team_master_python
    pythonBin: python3
  s3:
    region: ap-northeast-1
    buckets:
      teamSeasonDateData: aws-s3-season-csv
      teamData: aws-s3-team-csv
      teamMemberData: aws-s3-team-member-csv
      outputs: aws-s3-outputs-csv
      future: aws-s3-future-csv
      stats: aws-s3-stat-csv
      allLeague: aws-s3-all-league-csv
  
spring:
  flyway:
    enabled: true
    datasource:
      url: jdbc:postgresql://localhost:54320/soccer_bm
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true