app:
  csv-folder: /Users/shiraishitoshio/bookmaker/csv/
  output-csv-folder: /Users/shiraishitoshio/bookmaker/outputs/
  team-csv-folder: /Users/shiraishitoshio/bookmaker/teams_by_league/
  future-csv-folder: /Users/shiraishitoshio/bookmaker/future/
  b001-json-folder: /Users/shiraishitoshio/bookmaker/json/b001/

spring:
  datasource:
    bm:
      jdbc-url: jdbc:postgresql://localhost:54320/soccer_bm
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver

    master:
      jdbc-url: jdbc:postgresql://localhost:54320/soccer_bm_master
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    url: jdbc:postgresql://localhost:54320/soccer_bm_master
    user: postgres
    password: sonic3717
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
