spring:
  datasource:
    bm:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:bm;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS soccer_bm\;SET SCHEMA soccer_bm
      username: sa
      password:

  # （JPAを使っている場合だけ）テスト起動時にDDL自動生成したいなら
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

exportcsv:
  local-only: true