app:
  csv-folder: /Users/shiraishitoshio/bookmaker/csv/
  output-csv-folder: /Users/shiraishitoshio/bookmaker/outputs/
  team-csv-folder: /Users/shiraishitoshio/bookmaker/teams_by_league/
  future-csv-folder: /Users/shiraishitoshio/bookmaker/future/
  b001-json-folder: /Users/shiraishitoshio/bookmaker/json/b001/
  
process:
  python:
    root: /Users/shiraishitoshio/bookmaker/team_master_python
    pythonBin: python3
  s3:
    region: ap-northeast-1
    buckets:
      teamSeasonDateData: aws-s3-team-season-date-data
      teamData: aws-s3-team-data
      teamMemberData: aws-s3-team-member-data
      outputs: aws-s3-outputs

server:
  port: 8080

spring:
  datasource:
    bm:
      url: jdbc:postgresql://localhost:54320/soccer_bm
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver
    master:
      url: jdbc:postgresql://localhost:54320/soccer_bm_master
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver
    user:
      url: jdbc:postgresql://localhost:54320/soccer_bm_user
      username: postgres
      password: sonic3717
      driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:postgresql://localhost:54320/soccer_bm
    user: postgres
    password: sonic3717
    driver-class-name: org.postgresql.Driver

mybatis:
  type-handlers-package: dev.application.mybatis
  configuration:
    map-underscore-to-camel-case: true

security:
  jwt:
    issuer: bookmakers-web
    secret: "change-this-to-very-long-random-string-please"
    expires-in: 3600
