spring:
  flyway:
    enabled: false

  datasource:
    bm:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:bm;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
      username: sa
      password:

    master:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:master;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
      username: sa
      password:

    user:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:user;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
      username: sa
      password:

  # （JPAを使っている場合だけ）テスト起動時にDDL自動生成したいなら
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
